using System.ComponentModel.DataAnnotations;

namespace Gateway.API.DTOs.Writer;

public class ConversationResponse
{
  public Guid Id { get; set; }
  public string Title { get; set; } = string.Empty;
  public int TitleGenCount { get; set; }
  public bool IsTitleManual { get; set; }
  public DateTime CreatedAt { get; set; }
  public DateTime UpdatedAt { get; set; }
}

public class ConversationDetailResponse
{
  public Guid Id { get; set; }
  public string Title { get; set; } = string.Empty;
  public int TitleGenCount { get; set; }
  public bool IsTitleManual { get; set; }
  public DateTime CreatedAt { get; set; }
  public DateTime UpdatedAt { get; set; }
  public List<MessageResponse> Messages { get; set; } = [];
}

public class MessageResponse
{
  public Guid Id { get; set; }
  public string Role { get; set; } = string.Empty;
  public string Content { get; set; } = string.Empty;
  public DateTime CreatedAt { get; set; }
  public DateTime UpdatedAt { get; set; }
}

public class CreateConversationRequest
{
  [MaxLength(200)]
  public string? Title { get; set; }
}

public class UpdateConversationTitleRequest
{
  [Required]
  [MaxLength(200)]
  public string Title { get; set; } = string.Empty;
  public bool IsAutoGenerated { get; set; } = false;
}

public class SaveMessageRequest
{
  [Required]
  public string Role { get; set; } = string.Empty;

  [Required]
  public string Content { get; set; } = string.Empty;
}

public class BatchDeleteRequest
{
  [Required]
  [MinLength(1)]
  public List<Guid> Ids { get; set; } = [];
}

public class GenerateTitleResponse
{
  public string Title { get; set; } = string.Empty;
  public int RelevanceScore { get; set; }
  public bool Updated { get; set; }
}
