# pylint: disable=no-member,invalid-name,undefined-variable
# alembic.op is a runtime proxy; pgvector module is loaded but not statically
# resolved by pylint when accessed via `pgvector.sqlalchemy.vector.VECTOR`.
"""initial rag schema (documents, chunks for level2 and level3)

Revision ID: c41151e7fb0c
Revises:
Create Date: 2026-06-30 18:28:42.122151

Manual additions on top of autogenerate:
  1. `import pgvector.sqlalchemy` so VECTOR column type resolves.
  2. `CREATE EXTENSION IF NOT EXISTS vector` so a fresh DB without prior
     manual setup still works (Faz 1 created it by hand, but the migration
     should be self-sufficient for any future environment).
  3. HNSW indexes on chunks.embedding for ANN cosine search. Alembic
     autogenerate cannot emit operator classes (vector_cosine_ops) nor
     storage parameters (m, ef_construction), so we add them via
     op.execute() blocks below.
"""

from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401  # used as pgvector.sqlalchemy.vector.VECTOR below
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c41151e7fb0c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension exists. Safe no-op if already installed.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("app_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        schema="rag_level2_writer",
    )
    op.create_index(
        "ix_documents_user_conv",
        "documents",
        ["user_id", "conversation_id", "created_at"],
        unique=False,
        schema="rag_level2_writer",
    )
    op.create_index(
        op.f("ix_documents_user_id"),
        "documents",
        ["user_id"],
        unique=False,
        schema="rag_level2_writer",
    )
    op.create_table(
        "documents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("app_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        schema="rag_level3_chatbot",
    )
    op.create_index(
        "ix_documents_user_conv",
        "documents",
        ["user_id", "conversation_id", "created_at"],
        unique=False,
        schema="rag_level3_chatbot",
    )
    op.create_index(
        op.f("ix_documents_user_id"),
        "documents",
        ["user_id"],
        unique=False,
        schema="rag_level3_chatbot",
    )
    op.create_table(
        "chunks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["rag_level2_writer.documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_doc_idx"),
        schema="rag_level2_writer",
    )
    op.create_index(
        "ix_chunks_document_id",
        "chunks",
        ["document_id"],
        unique=False,
        schema="rag_level2_writer",
    )
    op.create_table(
        "chunks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["rag_level3_chatbot.documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_doc_idx"),
        schema="rag_level3_chatbot",
    )
    op.create_index(
        "ix_chunks_document_id",
        "chunks",
        ["document_id"],
        unique=False,
        schema="rag_level3_chatbot",
    )
    # ### end Alembic commands ###

    # ── HNSW vector indexes (manual; autogenerate does not emit these) ──
    # `vector_cosine_ops` enables fast cosine-distance ANN search, matching
    # how we'll query at runtime (embedding <=> query_embedding).
    # m = max connections per layer; ef_construction = build-time accuracy.
    # 16 / 64 are the pgvector recommended defaults; bump later if recall
    # measurements demand it.
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw "
        "ON rag_level2_writer.chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw "
        "ON rag_level3_chatbot.chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    # Drop HNSW indexes first so dropping the parent tables doesn't choke.
    op.execute("DROP INDEX IF EXISTS rag_level3_chatbot.ix_chunks_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS rag_level2_writer.ix_chunks_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chunks_document_id", table_name="chunks", schema="rag_level3_chatbot"
    )
    op.drop_table("chunks", schema="rag_level3_chatbot")
    op.drop_index(
        "ix_chunks_document_id", table_name="chunks", schema="rag_level2_writer"
    )
    op.drop_table("chunks", schema="rag_level2_writer")
    op.drop_index(
        op.f("ix_documents_user_id"),
        table_name="documents",
        schema="rag_level3_chatbot",
    )
    op.drop_index(
        "ix_documents_user_conv", table_name="documents", schema="rag_level3_chatbot"
    )
    op.drop_table("documents", schema="rag_level3_chatbot")
    op.drop_index(
        op.f("ix_documents_user_id"), table_name="documents", schema="rag_level2_writer"
    )
    op.drop_index(
        "ix_documents_user_conv", table_name="documents", schema="rag_level2_writer"
    )
    op.drop_table("documents", schema="rag_level2_writer")
    # ### end Alembic commands ###
