using Gateway.API.Data;
using Gateway.API.DTOs.Writer;
using Gateway.API.Entities;
using Microsoft.EntityFrameworkCore;

namespace Gateway.API.Services;

/// <summary>
/// Handles Writer app conversation CRUD operations.
/// </summary>
public class WriterConversationService
{
  private readonly AppDbContext _db;

  public WriterConversationService(AppDbContext db)
  {
    _db = db;
  }

  /// <summary>
  /// Returns all conversations for a user, ordered by most recent first.
  /// </summary>
  public async Task<List<ConversationResponse>> GetConversationsAsync(Guid userId)
  {
    return await _db.WriterConversations
      .Where(c => c.UserId == userId)
      .OrderByDescending(c => c.UpdatedAt)
      .Select(c => new ConversationResponse
      {
        Id = c.Id,
        Title = c.Title,
        TitleGenCount = c.TitleGenCount,
        IsTitleManual = c.IsTitleManual,
        CreatedAt = c.CreatedAt,
        UpdatedAt = c.UpdatedAt,
      })
      .ToListAsync();
  }

  /// <summary>
  /// Returns a single conversation with all its messages.
  /// </summary>
  public async Task<ConversationDetailResponse?> GetConversationAsync(Guid userId, Guid conversationId)
  {
    return await _db.WriterConversations
      .Where(c => c.Id == conversationId && c.UserId == userId)
      .Select(c => new ConversationDetailResponse
      {
        Id = c.Id,
        Title = c.Title,
        TitleGenCount = c.TitleGenCount,
        IsTitleManual = c.IsTitleManual,
        CreatedAt = c.CreatedAt,
        UpdatedAt = c.UpdatedAt,
        Messages = c.Messages
          .OrderBy(m => m.CreatedAt)
          .Select(m => new MessageResponse
          {
            Id = m.Id,
            Role = m.Role,
            Content = m.Content,
            CreatedAt = m.CreatedAt,
            UpdatedAt = m.UpdatedAt,
          })
          .ToList(),
      })
      .FirstOrDefaultAsync();
  }

  /// <summary>
  /// Creates a new conversation. Title is optional — auto-generated later.
  /// </summary>
  public async Task<ConversationResponse> CreateConversationAsync(Guid userId, CreateConversationRequest request)
  {
    var conversation = new WriterConversation
    {
      Id = Guid.NewGuid(),
      UserId = userId,
      Title = request.Title ?? "New chat",
      TitleGenCount = 0,
      IsTitleManual = request.Title is not null,
      CreatedAt = DateTime.UtcNow,
      UpdatedAt = DateTime.UtcNow,
    };

    _db.WriterConversations.Add(conversation);
    await _db.SaveChangesAsync();

    return new ConversationResponse
    {
      Id = conversation.Id,
      Title = conversation.Title,
      TitleGenCount = conversation.TitleGenCount,
      IsTitleManual = conversation.IsTitleManual,
      CreatedAt = conversation.CreatedAt,
      UpdatedAt = conversation.UpdatedAt,
    };
  }

  /// <summary>
  /// Renames a conversation. Marks title as manual (stops auto-update).
  /// </summary>
  public async Task<bool> UpdateTitleAsync(Guid userId, Guid conversationId, UpdateConversationTitleRequest request)
  {
    var conversation = await _db.WriterConversations
      .FirstOrDefaultAsync(c => c.Id == conversationId && c.UserId == userId);

    if (conversation is null) return false;

    conversation.Title = request.Title;
    conversation.UpdatedAt = DateTime.UtcNow;

    if (request.IsAutoGenerated)
    {
      conversation.TitleGenCount++;
    }
    else
    {
      conversation.IsTitleManual = true;
    }

    await _db.SaveChangesAsync();
    return true;
  }

  /// <summary>
  /// Updates the auto-generated title if the new one scores higher.
  /// </summary>
  public async Task<(bool updated, string title)> UpdateAutoTitleAsync(
    Guid userId, Guid conversationId, string newTitle, int newScore, int oldScore)
  {
    var conversation = await _db.WriterConversations
      .FirstOrDefaultAsync(c => c.Id == conversationId && c.UserId == userId);

    if (conversation is null) return (false, string.Empty);

    // Do not auto-update if user manually set the title or limit reached
    if (conversation.IsTitleManual || conversation.TitleGenCount >= 3)
      return (false, conversation.Title);

    var shouldUpdate = conversation.TitleGenCount == 0 || newScore >= oldScore * 1.3;

    if (shouldUpdate)
    {
      conversation.Title = newTitle;
    }

    conversation.TitleGenCount++;
    conversation.UpdatedAt = DateTime.UtcNow;
    await _db.SaveChangesAsync();

    return (shouldUpdate, conversation.Title);
  }

  /// <summary>
  /// Deletes a single conversation and all its messages (cascade).
  /// </summary>
  public async Task<bool> DeleteConversationAsync(Guid userId, Guid conversationId)
  {
    var conversation = await _db.WriterConversations
      .FirstOrDefaultAsync(c => c.Id == conversationId && c.UserId == userId);

    if (conversation is null) return false;

    _db.WriterConversations.Remove(conversation);
    await _db.SaveChangesAsync();
    return true;
  }

  /// <summary>
  /// Deletes multiple conversations at once.
  /// </summary>
  public async Task<int> BatchDeleteAsync(Guid userId, List<Guid> ids)
  {
    return await _db.WriterConversations
      .Where(c => c.UserId == userId && ids.Contains(c.Id))
      .ExecuteDeleteAsync();
  }

  /// <summary>
  /// Saves a message to a conversation and updates the conversation timestamp.
  /// </summary>
  public async Task<MessageResponse?> SaveMessageAsync(Guid userId, Guid conversationId, SaveMessageRequest request)
  {
    var conversation = await _db.WriterConversations
      .FirstOrDefaultAsync(c => c.Id == conversationId && c.UserId == userId);

    if (conversation is null) return null;

    var message = new WriterMessage
    {
      Id = Guid.NewGuid(),
      ConversationId = conversationId,
      Role = request.Role,
      Content = request.Content,
      CreatedAt = DateTime.UtcNow,
      UpdatedAt = DateTime.UtcNow,
    };

    _db.WriterMessages.Add(message);
    conversation.UpdatedAt = DateTime.UtcNow;
    await _db.SaveChangesAsync();

    return new MessageResponse
    {
      Id = message.Id,
      Role = message.Role,
      Content = message.Content,
      CreatedAt = message.CreatedAt,
      UpdatedAt = message.UpdatedAt,
    };
  }

  /// <summary>
  /// Searches conversations by title or message content.
  /// </summary>
  public async Task<List<ConversationResponse>> SearchAsync(Guid userId, string query)
  {
    var lowerQuery = query.ToLowerInvariant();

    return await _db.WriterConversations
      .Where(c => c.UserId == userId &&
        (c.Title.ToLower().Contains(lowerQuery) ||
         c.Messages.Any(m => m.Content.ToLower().Contains(lowerQuery))))
      .OrderByDescending(c => c.UpdatedAt)
      .Select(c => new ConversationResponse
      {
        Id = c.Id,
        Title = c.Title,
        TitleGenCount = c.TitleGenCount,
        IsTitleManual = c.IsTitleManual,
        CreatedAt = c.CreatedAt,
        UpdatedAt = c.UpdatedAt,
      })
      .ToListAsync();
  }
}
