import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';
import {
  Conversation,
  ConversationDetail,
  ConversationMessage,
  GenerateTitleResult,
} from '../models/conversation.model';

@Injectable({
  providedIn: 'root',
})
export class ConversationService {
  private http = inject(HttpClient);
  private gatewayUrl = environment.gatewayUrl;
  private writerApiUrl = environment.gatewayUrl
    ? `${environment.gatewayUrl}/apps/writer/api`
    : environment.apiUrl;

  // ─── Gateway CRUD ────────────────────────────────

  getConversations(): Observable<Conversation[]> {
    return this.http.get<Conversation[]>(`${this.gatewayUrl}/api/writer/conversations`);
  }

  getConversation(id: string): Observable<ConversationDetail> {
    return this.http.get<ConversationDetail>(
      `${this.gatewayUrl}/api/writer/conversations/${id}`,
    );
  }

  createConversation(title?: string): Observable<Conversation> {
    return this.http.post<Conversation>(`${this.gatewayUrl}/api/writer/conversations`, {
      title: title ?? null,
    });
  }

  updateTitle(id: string, title: string, isAutoGenerated = false): Observable<{ message: string }> {
    return this.http.patch<{ message: string }>(
      `${this.gatewayUrl}/api/writer/conversations/${id}/title`,
      { title, isAutoGenerated },
    );
  }

  deleteConversation(id: string): Observable<{ message: string }> {
    return this.http.delete<{ message: string }>(
      `${this.gatewayUrl}/api/writer/conversations/${id}`,
    );
  }

  batchDelete(ids: string[]): Observable<{ message: string; count: number }> {
    return this.http.post<{ message: string; count: number }>(
      `${this.gatewayUrl}/api/writer/conversations/batch-delete`,
      { ids },
    );
  }

  saveMessage(
    conversationId: string,
    role: string,
    content: string,
  ): Observable<ConversationMessage> {
    return this.http.post<ConversationMessage>(
      `${this.gatewayUrl}/api/writer/conversations/${conversationId}/messages`,
      { role, content },
    );
  }

  searchConversations(query: string): Observable<Conversation[]> {
    return this.http.get<Conversation[]>(
      `${this.gatewayUrl}/api/writer/conversations/search`,
      { params: { q: query } },
    );
  }

  // ─── Writer Backend (AI) ─────────────────────────

  generateTitle(
    messages: { role: string; content: string }[],
    currentTitle: string,
  ): Observable<GenerateTitleResult> {
    return this.http.post<GenerateTitleResult>(`${this.writerApiUrl}/generate-title`, {
      messages,
      current_title: currentTitle,
    });
  }
}
